  version: "3"

  services:
    app:
      build:
        context: .
        dockerfile: Dockerfile
      image: sandboxapp
      container_name: app
      restart: unless-stopped
      volumes:
        - ./src/:/var/www

    webserver:
      image: nginx:alpine
      container_name: webserver
      restart: unless-stopped
      ports:
        - "8080:80"
      volumes:
        - ./src/:/var/www
        - ./config/nginx/:/etc/nginx/conf.d
      depends_on:
        - app
