# Development configuration, don't use on production
  version: "3"

  services:
    psqldb:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: d;%f=68ZXJENER-R
        PGDATA: /var/lib/postgresql/data/pgdata
      volumes:
        - ./docker/.data/pgsql/:/var/lib/postgresql/data/
    phpapp:
      build:
        context: ./docker/php-fpm/
        dockerfile: Dockerfile_dev
      restart: unless-stopped
      volumes:
        - ./phpcode/:/var/www/
      environment:
        DB_HOST: psqldb
        POSTGRES_PASSWORD: d;%f=68ZXJENER-R
        DEBUG_MODE: 1
      volumes:
        - ./docker/php-fpm/config/zzz-phpSettings.conf:/usr/local/etc/php-fpm.d/zzz-phpSettings.conf
        - ./docker/.log/phpfpm/:/var/log/
        - ./phpcode/:/var/www
      depends_on:
        - psqldb
    nextapp:
      build:
        context: ./docker/nextapp
        dockerfile: Dockerfile_dev
      restart: unless-stopped
      ports:
        - "3000:3000"
      volumes:
        - ./next-app:/app
    webserver:
      build:
        context: ./docker/nginx
        dockerfile: Dockerfile_dev
      restart: unless-stopped
      ports:
        - "8000:80"
      volumes:
        - ./phpcode/:/var/www
        - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        - ./docker/.log/nginx/:/var/log/nginx/
      depends_on:
        - phpapp
        - nextapp