  version: "3"

  services:
    psqldb:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: d;%f=68ZXJENER-R
        PGDATA: /var/lib/postgresql/data/pgdata
      volumes:
        - ./docker/pgsql/data/:/var/lib/postgresql/data/
    phpapp:
      build:
        context: ./docker/php-fpm/
        dockerfile: Dockerfile
      restart: unless-stopped
      volumes:
        - ./server/:/var/www/
      environment:
        DB_HOST: psqldb
        POSTGRES_PASSWORD: d;%f=68ZXJENER-R
        DEBUG_MODE: 1
      depends_on:
        - psqldb
    webserver:
      image: nginx:alpine
      restart: unless-stopped
      ports:
        - "8001:80"
      volumes:
        - ./server/:/var/www
        - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      depends_on:
        - phpapp